# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoginClient = channel.unary_unary(
                '/ChatService/LoginClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.CreateAccountClient = channel.unary_unary(
                '/ChatService/CreateAccountClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.DeleteAccountClient = channel.unary_unary(
                '/ChatService/DeleteAccountClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.ListAccountClient = channel.unary_unary(
                '/ChatService/ListAccountClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.SendMessageClient = channel.unary_unary(
                '/ChatService/SendMessageClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.ViewMessageClient = channel.unary_unary(
                '/ChatService/ViewMessageClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.LogoutClient = channel.unary_unary(
                '/ChatService/LogoutClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.QuitClient = channel.unary_unary(
                '/ChatService/QuitClient',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )
        self.ChatStream = channel.unary_stream(
                '/ChatService/ChatStream',
                request_serializer=chat__pb2.Empty.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoginClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccountClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccountClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccountClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessageClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewMessageClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuitClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoginClient': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'CreateAccountClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'DeleteAccountClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccountClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'ListAccountClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccountClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'SendMessageClient': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessageClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'ViewMessageClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewMessageClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'LogoutClient': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'QuitClient': grpc.unary_unary_rpc_method_handler(
                    servicer.QuitClient,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=chat__pb2.Empty.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoginClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/LoginClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccountClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/CreateAccountClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAccountClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/DeleteAccountClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAccountClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/ListAccountClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessageClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/SendMessageClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewMessageClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/ViewMessageClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/LogoutClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QuitClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatService/QuitClient',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/ChatStream',
            chat__pb2.Empty.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
