class ClientOperation:
  LOGIN = 0;
  CREATE_ACCOUNT = 1;
  DELETE_ACCOUNT = 2;
  LIST_ACCOUNTS = 3;
  SEND_MESSAGE = 4;
  VIEW_UNDELIVERED_MESSAGES = 5;
  LOGOUT = 6;
  QUIT_MESSENGER = 7;

  RECEIVE_CURRENT_MESSAGE = 8;

class ServerOperation:
  SUCCESS = 0;
  FAILURE = 1;
  ACCOUNT_ALREADY_EXISTS = 2;
  ACCOUNT_DOES_NOT_EXIST = 3;
  LIST_OF_ACCOUNTS = 4;
  LIST_OF_MESSAGES = 5;